### ISSUE TITLE
DNS gone missing

### ISSUE THREAD

**Issue by insightfuls** [Codeception/codeception.github.com#123]
The DNS for codeception.com seems to have gone missing. I guess there's probably meant to be an A or CNAME there or something. In any case, the site won't load. `codeception.github.com` redirects to `codeception.com`, too, so there's really no convenient way to access the documentation at the moment. Would be wonderful if this could be fixed up, even if just turning off the redirection and we have to use `codeception.github.com` for a while until the DNS can be fixed up for `codeception.com`.

**Comment by insightfuls** [comment]
Looks like it's correct now for `codeception.com`, and there is an MX record, too (which also didn't exist a day or two ago, as I tried emailing the devs at that domain and it bounced). `codeception.github.com` is redirecting and working.

However, `www.codeception.com` incorrectly has a `CNAME` with an IP address. It should either have an `A` record with the IP address, or a `CNAME` directing to a named host (though preferably NOT pointing to the bare domain `codeception.com`).

**Comment by Naktibalda** [comment]
Fixed

**Comment by insightfuls** [comment]
The `www` record is still incorrect, and still doesn't work for me. The bare domain, and via `codeception.github.com` both work, though, so this is at least partly fixed.
